spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    show-sql: false

healthtrack:
  jwt:
    # Set to true for production to prevent token transmission over unencrypted connections (HTTPS ONLY)
    cookie-secure: true
